/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAccordion: typeof import('./components/Base/BaseAccordion.vue')['default']
    BaseAlert: typeof import('./components/Base/BaseAlert.vue')['default']
    BaseAlertBanner: typeof import('./components/Base/BaseAlertBanner.vue')['default']
    BaseAuditLog: typeof import('./components/Base/BaseAuditLog.vue')['default']
    BaseBadge: typeof import('./components/Base/BaseBadge.vue')['default']
    BaseBarChart: typeof import('./components/Base/BaseBarChart.vue')['default']
    BaseBreadcrumb: typeof import('./components/Base/BaseBreadcrumb.vue')['default']
    BaseButton: typeof import('./components/Base/BaseButton.vue')['default']
    BaseCalendarView: typeof import('./components/Base/BaseCalendarView.vue')['default']
    BaseCard: typeof import('./components/Base/BaseCard.vue')['default']
    BaseChart: typeof import('./components/Base/BaseChart.vue')['default']
    BaseCheckbox: typeof import('./components/Base/BaseCheckbox.vue')['default']
    BaseColorPicker: typeof import('./components/Base/BaseColorPicker.vue')['default']
    BaseDashboardGrid: typeof import('./components/Base/BaseDashboardGrid.vue')['default']
    BaseDatepicker: typeof import('./components/Base/BaseDatepicker.vue')['default']
    BaseDivider: typeof import('./components/Base/BaseDivider.vue')['default']
    BaseDrawer: typeof import('./components/Base/BaseDrawer.vue')['default']
    BaseEmptyState: typeof import('./components/Base/BaseEmptyState.vue')['default']
    BaseFilterModal: typeof import('./components/Base/BaseFilterModal.vue')['default']
    BaseHighlightCard: typeof import('./components/Base/BaseHighlightCard.vue')['default']
    BaseInput: typeof import('./components/Base/BaseInput.vue')['default']
    BaseKanbanBoard: typeof import('./components/Base/BaseKanbanBoard.vue')['default']
    BaseLineChart: typeof import('./components/Base/BaseLineChart.vue')['default']
    BaseLoader: typeof import('./components/Base/BaseLoader.vue')['default']
    BaseModal: typeof import('./components/Base/BaseModal.vue')['default']
    BaseOtpInput: typeof import('./components/Base/BaseOtpInput.vue')['default']
    BasePagination: typeof import('./components/Base/BasePagination.vue')['default']
    BasePieChart: typeof import('./components/Base/BasePieChart.vue')['default']
    BasePopover: typeof import('./components/Base/BasePopover.vue')['default']
    BaseProgress: typeof import('./components/Base/BaseProgress.vue')['default']
    BaseRadio: typeof import('./components/Base/BaseRadio.vue')['default']
    BaseRating: typeof import('./components/Base/BaseRating.vue')['default']
    BaseReportTable: typeof import('./components/Base/BaseReportTable.vue')['default']
    BaseSelect: typeof import('./components/Base/BaseSelect.vue')['default']
    BaseSkeletonLoader: typeof import('./components/Base/BaseSkeletonLoader.vue')['default']
    BaseStatCard: typeof import('./components/Base/BaseStatCard.vue')['default']
    BaseStepper: typeof import('./components/Base/BaseStepper.vue')['default']
    BaseSwitch: typeof import('./components/Base/BaseSwitch.vue')['default']
    BaseTable: typeof import('./components/Base/BaseTable.vue')['default']
    BaseTabs: typeof import('./components/Base/BaseTabs.vue')['default']
    BaseTextarea: typeof import('./components/Base/BaseTextarea.vue')['default']
    BaseTimeline: typeof import('./components/Base/BaseTimeline.vue')['default']
    BaseTimePicker: typeof import('./components/Base/BaseTimePicker.vue')['default']
    BaseToast: typeof import('./components/Base/BaseToast.vue')['default']
    BaseTooltip: typeof import('./components/Base/BaseTooltip.vue')['default']
    BaseUpload: typeof import('./components/Base/BaseUpload.vue')['default']
    BaseUploadMultiple: typeof import('./components/Base/BaseUploadMultiple.vue')['default']
    DashboardNavbar: typeof import('./components/Layout/DashboardNavbar.vue')['default']
    DashboardNavbarActions: typeof import('./components/Layout/DashboardNavbarActions.vue')['default']
    DashboardNotifications: typeof import('./components/Layout/DashboardNotifications.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ModalForm: typeof import('./components/FormExample/ModalForm.vue')['default']
    NewsList: typeof import('./modules/berita/components/NewsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Layout/Sidebar.vue')['default']
    UserList: typeof import('./modules/user-management/components/UserList.vue')['default']
  }
}
